import React, { useState } from 'react';
import { 
  Share2, 
  X, 
  Copy, 
  Check, 
  Download, 
  MessageSquare, 
  FileText, 
  Mail, 
  CheckCircle2,
  Brain
} from 'lucide-react';
import { Incident, IncidentAnalysisResponse } from '../types';
import { playClickFeedback } from '../services/audio';

interface BroadcastModalProps {
  isOpen: boolean;
  onClose: () => void;
  incident: Incident;
  analysisResponse: IncidentAnalysisResponse | null;
}

export const BroadcastModal: React.FC<BroadcastModalProps> = ({
  isOpen,
  onClose,
  incident,
  analysisResponse
}) => {
  const [activeTab, setActiveTab] = useState<'slack' | 'postmortem' | 'jira'>('slack');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const analysis = analysisResponse?.analysis;
  const memories = analysisResponse?.retrieved_memories || [];

  // 1. Slack Format
  const slackMessage = `🚨 *INCIDENT ALERT: ${incident.incident_id}*
*Service:* \`${incident.service}\` | *Severity:* *${incident.severity}* | *Status:* *${incident.status}*
*Timestamp:* ${incident.timestamp || new Date().toISOString()}

📋 *Incident Commander Executive Summary:*
${analysis?.summary || 'Incident under active investigation by OpsMemory AI agent.'}

🔍 *Likely Root Cause (Confidence: ${analysis?.confidence || 'HIGH'}):*
${analysis?.likely_root_cause || incident.root_cause || 'Investigating system metrics and telemetry.'}

🧠 *Hindsight Persistent Memory Attribution:*
${memories.length > 0 
  ? memories.map(m => `• Cites *${m.incident_id}* (${m.service}): ${m.root_cause}`).join('\n')
  : '• No prior matching incident; registering new baseline memory.'}

🛠️ *Immediate Recommended Mitigation:*
${analysis?.recommended_resolution?.map(r => `• ${r}`).join('\n') || 'Refer to incident runbook.'}

*War Room URL:* http://localhost:8000
_Broadcasted automatically via OpsMemory AI Incident Response Agent_`;

  // 2. Comprehensive Postmortem Markdown Format
  const postmortemMarkdown = `# SRE Incident Postmortem: ${incident.incident_id} - ${incident.service}

**Incident ID:** ${incident.incident_id}  
**Target Service:** ${incident.service}  
**Severity:** ${incident.severity}  
**Status:** ${incident.status}  
**Date/Time:** ${incident.timestamp || new Date().toISOString()}  
**Memory Bank:** \`ops-memory\`  

---

## 1. Executive Summary
${analysis?.summary || 'Detailed summary of the operational disruption.'}

## 2. Observed Symptoms & Error Telemetry
### Operational Symptoms:
${incident.symptoms.map(s => `- ${s}`).join('\n')}

### Error Logs & Stack Traces:
\`\`\`
${incident.error_logs.join('\n')}
\`\`\`

## 3. Root Cause Analysis
**Likely Root Cause:**  
${analysis?.likely_root_cause || incident.root_cause || 'Pending postmortem finalization'}

**Assessment Confidence:** ${analysis?.confidence || 'HIGH'}

**Evidence-Based Reasoning:**  
${analysis?.reasoning_summary || 'Correlated operational telemetry with historical postmortems in Hindsight persistent memory.'}

## 4. Hindsight Historical Memory Attribution
${memories.length > 0 ? memories.map(m => `
### Referenced Memory: ${m.incident_id} (${m.service})
- **Historical Root Cause:** ${m.root_cause}
- **Proven Historical Fix:** ${m.resolution}
- **Key Lessons Learned:** ${m.lessons_learned}
- **Memory Provider:** ${m.source}
`).join('\n') : '*No prior matches; first occurrence.*'}

## 5. Mitigation & Diagnostic Runbook Execution
### Recommended Diagnostics:
${analysis?.recommended_investigation?.map(step => `- [x] ${step}`).join('\n') || '- Standard triage'}

### Applied Remediation:
${analysis?.recommended_resolution?.map(step => `- [x] ${step}`).join('\n') || '- System restored'}

## 6. Action Items & Lessons Learned
${incident.lessons_learned && incident.lessons_learned.length > 0 
  ? incident.lessons_learned.map(l => `- ${l}`).join('\n') 
  : '- Retain postmortem learnings in Hindsight memory bank for future incidents.'}

---
*Generated by OpsMemory v1.0.0 (Unified Localhost: http://localhost:8000)*
`;

  // 3. Jira / Ticket Format
  const jiraFormat = `h2. Incident Summary: ${incident.incident_id} (${incident.service})
*Severity:* ${incident.severity}
*Reported:* ${incident.timestamp || new Date().toISOString()}

h3. Symptoms & Error Telemetry:
${incident.symptoms.map(s => `* ${s}`).join('\n')}

h3. Root Cause Hypothesis:
${analysis?.likely_root_cause || 'Identified via OpsMemory Hindsight correlation'}

h3. Historical Precedent:
${memories.map(m => `* Correlates with ${m.incident_id}: ${m.root_cause}`).join('\n') || 'None recorded'}

h3. Verified Runbook Mitigation:
${analysis?.recommended_resolution?.map(r => `# ${r}`).join('\n') || 'N/A'}`;

  const currentContent = activeTab === 'slack' 
    ? slackMessage 
    : (activeTab === 'postmortem' ? postmortemMarkdown : jiraFormat);

  const handleCopy = () => {
    playClickFeedback();
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    playClickFeedback();
    const blob = new Blob([postmortemMarkdown], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `postmortem-${incident.incident_id}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div 
        className="w-full max-w-3xl glass-panel border border-white/10 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-5 py-4 bg-[#0B0F19] border-b border-white/[0.08] flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-purple-500/20 text-purple-400 flex items-center justify-center border border-purple-500/30">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                Incident Commander Broadcast & Export
              </h2>
              <p className="text-xs text-slate-400 mt-0.5">
                Generate formatted incident updates for Slack war rooms, engineering postmortems, or Jira tickets.
              </p>
            </div>
          </div>

          <button
            onClick={() => { playClickFeedback(); onClose(); }}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="px-5 pt-3 bg-[#080C14] border-b border-white/[0.06] flex items-center gap-2">
          <button
            onClick={() => { playClickFeedback(); setActiveTab('slack'); }}
            className={`px-3 py-2 rounded-t-lg text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
              activeTab === 'slack'
                ? 'border-purple-500 text-white bg-white/5'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5 text-purple-400" />
            Slack War Room Update
          </button>

          <button
            onClick={() => { playClickFeedback(); setActiveTab('postmortem'); }}
            className={`px-3 py-2 rounded-t-lg text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
              activeTab === 'postmortem'
                ? 'border-purple-500 text-white bg-white/5'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <FileText className="w-3.5 h-3.5 text-blue-400" />
            SRE Postmortem (.md)
          </button>

          <button
            onClick={() => { playClickFeedback(); setActiveTab('jira'); }}
            className={`px-3 py-2 rounded-t-lg text-xs font-semibold flex items-center gap-2 border-b-2 transition-all ${
              activeTab === 'jira'
                ? 'border-purple-500 text-white bg-white/5'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Mail className="w-3.5 h-3.5 text-emerald-400" />
            Jira Ticket / Email
          </button>
        </div>

        {/* Content Box */}
        <div className="p-5 overflow-y-auto flex-1 bg-[#05070C]">
          <div className="relative">
            <textarea
              readOnly
              value={currentContent}
              rows={16}
              className="w-full p-4 rounded-xl font-mono text-xs text-slate-200 bg-[#090D17] border border-white/10 focus:outline-none select-all leading-relaxed"
            />
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-5 py-3.5 bg-[#0B0F19] border-t border-white/[0.08] flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-slate-400">
            <Brain className="w-4 h-4 text-purple-400" />
            <span>Includes historical correlation with Hindsight memory bank</span>
          </div>

          <div className="flex items-center gap-2">
            {activeTab === 'postmortem' && (
              <button
                onClick={handleDownload}
                className="px-3.5 py-1.5 rounded-xl text-xs font-semibold bg-white/5 hover:bg-white/10 text-slate-300 border border-white/10 flex items-center gap-1.5 transition-all"
              >
                <Download className="w-3.5 h-3.5 text-purple-400" />
                Download Markdown (.md)
              </button>
            )}

            <button
              onClick={handleCopy}
              className="px-4 py-1.5 rounded-xl text-xs font-semibold bg-purple-600 hover:bg-purple-500 text-white flex items-center gap-1.5 shadow-lg shadow-purple-900/30 transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-white" /> : <Copy className="w-3.5 h-3.5 text-white" />}
              {copied ? 'Copied to Clipboard!' : 'Copy to Clipboard'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
